import logging
import time
from typing import Optional

from openoperator.action.base import ActionController
from openoperator.action.window_controller import WindowController
from openoperator.agent.base import AgentBrain
from openoperator.agent.visual_stasis_detector import VisualStasisDetector
from openoperator.core.models import ActionIntent
from openoperator.perception.base import PerceptionEngine

logger = logging.getLogger(__name__)


class OpenOperator:
    """
    Main orchestrator class that coordinates the autonomous execution loop.
    
    It manages the flow of data strictly from Perception -> Agent -> Action,
    relying exclusively on visual data to determine the next system interaction.
    """

    def __init__(
        self,
        perception: PerceptionEngine,
        controller: ActionController,
        brain: AgentBrain,
        window_controller: Optional[WindowController] = None,
    ) -> None:
        self.perception = perception
        self.controller = controller
        self.brain = brain
        # Inject the new native Windows controller
        self.window_controller = window_controller or WindowController()
        # Initialize the Stasis Detector (Issue #67)
        self.stasis_detector = VisualStasisDetector(max_history=3)

    def execute_task(self, goal: str, max_steps: int = 20) -> bool:
        """
        Executes a user-defined goal by running the core autonomous loop.

        Args:
            goal (str): The natural language instruction for the agent.
            max_steps (int): Protection mechanism against infinite loops.

        Returns:
            bool: True if the agent successfully completed the task,
                  False if the task failed or hit the max step limit.
        """
        logger.info(f"Starting execution for goal: '{goal}'")
        logger.debug(f"Max steps configured: {max_steps}")

        # Reset stasis history before starting a new task
        self.stasis_detector.clear()

        for step in range(1, max_steps + 1):
            logger.info(f"--- Step {step}/{max_steps} ---")
            
            try:
                logger.debug("Capturing screen state...")
                image_data = self.perception.capture_screen()

                # Generate a string representation of the screen for stasis detection
                # Converts image bytes to a hash to quickly detect completely static screens
                obs_rep = str(hash(image_data.tobytes())) if hasattr(image_data, "tobytes") else str(image_data)
                self.stasis_detector.add_observation(obs_rep)

                if self.stasis_detector.is_in_stasis():
                    logger.error("Visual Stasis Detected! The agent is stuck in a loop. Aborting task.")
                    return False

                logger.debug("Querying agent brain for next action...")
                intent = self.brain.decide_next_action(goal, image_data)
                logger.info(f"Agent decided action: {intent.action_type}")

                if intent.action_type.lower() == "done":
                    logger.info(f"Goal achieved successfully in {step} steps.")
                    return True

                self._execute_intent(intent)
                
                time.sleep(1.0)

            except Exception as e:
                logger.error(f"Execution failed during step {step}: {e}", exc_info=True)
                return False

        logger.warning(f"Task aborted: Hit maximum step limit of {max_steps}.")
        return False

    def _execute_intent(self, intent: ActionIntent) -> None:
        """
        Routes the structured ActionIntent to the appropriate controller methods.

        Args:
            intent (ActionIntent): The command object generated by the AgentBrain.
        """
        action = intent.action_type.lower()

        if action == "click":
            if intent.coordinates:
                x, y = intent.coordinates
                logger.debug(f"Moving mouse to ({x}, {y}) before clicking.")
                self.controller.move_mouse(x, y)
                time.sleep(0.2)
            
            logger.debug("Executing click.")
            self.controller.click("left")

        elif action == "type":
            if intent.coordinates:
                x, y = intent.coordinates
                logger.debug(f"Moving mouse to ({x}, {y}) and clicking to focus.")
                self.controller.move_mouse(x, y)
                time.sleep(0.2)
                self.controller.click("left")
                time.sleep(0.2)
                
            if intent.input_text:
                logger.debug(f"Typing text: '{intent.input_text}'")
                self.controller.type_text(intent.input_text)
            else:
                logger.error("Action intent specified 'type' but no input_text was provided.")

        elif action == "move":
            if intent.coordinates:
                x, y = intent.coordinates
                logger.debug(f"Moving mouse to ({x}, {y}).")
                self.controller.move_mouse(x, y)
            else:
                logger.error("Action intent specified 'move' but no coordinates were provided.")

        elif action in ("focus", "switch_window"):
            if intent.input_text:
                logger.debug(f"Attempting to focus window matching: '{intent.input_text}'")
                success = self.window_controller.focus_window_by_title(intent.input_text)
                if not success:
                    logger.warning(f"Could not find or focus window matching '{intent.input_text}'.")
            else:
                logger.error("Action intent specified window focus but no input_text (title) was provided.")

        elif action == "wait":
            logger.debug("Agent requested a wait action. Sleeping for 3 seconds.")
            time.sleep(3.0)

        else:
            logger.warning(f"Unsupported action type received: '{action}'")